Change tree to blob for colab access
Fix the error when opening in colab, the following message is shown
```
malformed GitHub path: missing 'blob' before branch name: JohnsonBiophysicsLab/ionerdss/tree/main/docs/Run_NERDSS_colab.ipynb
Error: malformed GitHub path: missing 'blob' before branch name: JohnsonBiophysicsLab/ionerdss/tree/main/docs/Run_NERDSS_colab.ipynb
    at oXa (https://ssl.gstatic.com/colaboratory-static/common/250546843e36e346a6470f73fa201ff0/external_binary_l10n__zh_cn.js:2275:61)
    at l7.createFileIdFromPathParts (https://ssl.gstatic.com/colaboratory-static/common/250546843e36e346a6470f73fa201ff0/external_binary_l10n__zh_cn.js:7561:253)
    at FL (https://ssl.gstatic.com/colaboratory-static/common/250546843e36e346a6470f73fa201ff0/external_binary_l10n__zh_cn.js:2284:241)
    at HL (https://ssl.gstatic.com/colaboratory-static/common/250546843e36e346a6470f73fa201ff0/external_binary_l10n__zh_cn.js:2285:87)
    at IL (https://ssl.gstatic.com/colaboratory-static/common/250546843e36e346a6470f73fa201ff0/external_binary_l10n__zh_cn.js:2285:232)
    at https://ssl.gstatic.com/colaboratory-static/common/250546843e36e346a6470f73fa201ff0/external_binary_l10n__zh_cn.js:8430:265
    at https://ssl.gstatic.com/colaboratory-static/common/250546843e36e346a6470f73fa201ff0/external_binary_l10n__zh_cn.js:8430:760

```